name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
            
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote
          
      - name: Exm GH Action?
        run: |
          (sleep 4; sudo dmesg; sudo ps aux; ) &
          tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w 8 | head -n 1
          echo "fuck2"
          kill -9 %1  
        
      - name: Install dependencies
        run: |
          cd MagiskOnWSALocal/scripts
          sudo apt-get update && sudo apt-get install -y whiptail setools lzip wine winetricks patchelf e2fsprogs python3-pip aria2 p7zip-full attr expect-dev
          pip list --disable-pip-version-check | grep -E "^requests " >/dev/null 2>&1 || python3 -m pip install requests
      
      - name: Build Magisk On WSA
        run: |
          cd MagiskOnWSALocal/scripts
          
          echo "fuck urandom"
          tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w 8 | head -n 1
          
          # prepare WineTrick
          echo '
            export SHELL="/bin/bash"
            export TERM="xterm-256color"
            tty; export;
            
            winetricks list-installed | grep -E "^msxml6" >/dev/null 2>&1 || {
              cp -r ../wine/.cache/* ~/.cache
              winetricks msxml6 || abort
            }
            bash -x ./build.sh \
              --arch x64 \
              --release-type WIF \
              --magisk-ver beta \
              --gapps-brand MindTheGapps \
              --gapps-variant pico \
              --remove-amazon \
              --root-sol magisk \
              --compress \
          ' | python3 -c 'import pty; pty.spawn(["/bin/bash", "-i", "-s"])'
                  
          ls -l ../output
      
      - name: Generate timestamp
        id: timestamp # output: value
        run: |
          TIMESTAMP="$(date +"%Y%m%d")"
          echo "Timestamp: ${TIMESTAMP}"
          echo "::set-output name=value::${TIMESTAMP}"
      - name: Create New Release and Upload
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*"
          name: "${{ format('WSA: {0}', steps.timestamp.outputs.value) }}"
          tag: $${{ steps.timestamp.outputs.value }}
          commit: ${{ github.sha }}
          #prerelease: true
          allowUpdates: true

          # XXX: edit this to false & true if you want to preserve original artifact
          removeArtifacts: true
          replacesArtifacts: false
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}
